### ISSUE TITLE
base of the logarithm is wrong

### ISSUE THREAD

**Issue by seyma-tas** [learn-co-curriculum/dsc-entropy-and-information-gain#1]
𝑝(𝑦𝑒𝑠)=−(9/14)𝑙𝑜𝑔2(9/14)=0.28 In the formula you wrote base = 2 but you did the calculations in base = e(natural logarithm). This mistake continues in the lab of the same  lesson.

**Comment by jessepisel** [comment]
Fixed with [8ca4e30](https://github.com/learn-co-curriculum/dsc-entropy-and-information-gain/commit/8ca4e30c2b17130bbcce2b9b9649a1d53fc81058)
